# Generated by Django 5.1 on 2024-08-08 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_upload', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mediafile',
            old_name='created_at',
            new_name='uploaded_at',
        ),
        migrations.RemoveField(
            model_name='mediafile',
            name='name',
        ),
    ]
